#!/usr/bin/env bash
set -u
set +e

# Runs the checker against the two Hadoop sample datasets generated by
# `generate_hadoop_offset_gap_sample_data.sh`.
#
# Expected results:
#   - pass roots exit 0.
#   - gap roots exit 1 and print missing_offsets=[1] for partition 0.
#
# Usage:
#   RUN_DATE=2026-07-02 scripts/run_hadoop_offset_gap_sample_checks.sh hdfs:///tmp/recon-offset-samples

SPARK_SHELL_BIN="${SPARK_SHELL_BIN:-spark-shell}"
SPARK_MASTER="${SPARK_MASTER:-yarn}"
SPARK_SQL_TIMEZONE="${SPARK_SQL_TIMEZONE:-UTC}"
SAMPLE_OUTPUT_ROOT="${1:-${SAMPLE_OUTPUT_ROOT:-hdfs:///tmp/recon-kafka-offset-gap-samples}}"
RUN_DATE="${RUN_DATE:-$(date +%F)}"
METADATA_COLUMN="${METADATA_COLUMN:-cactus__metadata}"
DATE_PARTITION_COLUMN="${DATE_PARTITION_COLUMN:-timestampcolumn}"
MISSING_OFFSETS_LIMIT="${MISSING_OFFSETS_LIMIT:-1000}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHECKER="$SCRIPT_DIR/check_kafka_offset_gaps.scala"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  sed -n '3,14p' "$0"
  exit 0
fi

# Runs one sample scenario and checks that the checker exits with the expected code.
run_expected() {
  local name="$1"
  local expected_exit="$2"
  local roots="$3"
  shift 3

  echo "[recon-sample-check] scenario=$name expected_exit=$expected_exit roots=$roots"
  "$SPARK_SHELL_BIN" \
    --master "$SPARK_MASTER" \
    --conf "spark.sql.session.timeZone=$SPARK_SQL_TIMEZONE" \
    --conf "spark.recon.inputRoots=$roots" \
    --conf "spark.recon.metadataColumn=$METADATA_COLUMN" \
    --conf "spark.recon.datePartitionColumn=$DATE_PARTITION_COLUMN" \
    --conf "spark.recon.runDate=$RUN_DATE" \
    --conf "spark.recon.missingOffsetsLimit=$MISSING_OFFSETS_LIMIT" \
    "$@" \
    -i "$CHECKER"
  local observed_exit=$?

  echo "[recon-sample-check] scenario=$name observed_exit=$observed_exit"
  if [[ "$observed_exit" != "$expected_exit" ]]; then
    echo "[recon-sample-check] ERROR: scenario=$name expected_exit=$expected_exit observed_exit=$observed_exit" >&2
    return 1
  fi
  return 0
}

failures=0

pass_roots="$SAMPLE_OUTPUT_ROOT/pass/root_a,$SAMPLE_OUTPUT_ROOT/pass/root_b"
gap_roots="$SAMPLE_OUTPUT_ROOT/gap/root_a,$SAMPLE_OUTPUT_ROOT/gap/root_b"

run_expected "multi_root_pass" 0 "$pass_roots" || failures=$((failures + 1))
run_expected "multi_root_gap" 1 "$gap_roots" || failures=$((failures + 1))

if [[ "$failures" -ne 0 ]]; then
  echo "[recon-sample-check] failures=$failures" >&2
  exit 1
fi

echo "[recon-sample-check] all sample checks matched expected exits"
